### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by ghost** [sarchar/addressgen#2]
[root@localhost addressgen]# python3 genaddress.py -p asdf
Segmentation fault

what might be issue. ?

[root@localhost addressgen]# python -m pdb genaddress.py
> /home/deploy/addressgen/genaddress.py(2)<module>()
-> import argparse

**Comment by ghost** [comment]
tried on another server .

# python3 genaddress.py
Traceback (most recent call last):
  File "genaddress.py", line 456, in <module>
    main()
  File "genaddress.py", line 411, in main
    public_key, private_key = gen_key_pair()
  File "genaddress.py", line 95, in gen_key_pair
    raise Exception("internal error")
Exception: internal error

**Comment by nanoelf** [comment]
I have the same issue, not sure what the problem could be.
